# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- Config

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Task to install the DotNet Core version to run this yml 
#- task: DotNetCoreInstaller@0
#  inputs:
#    version: '2.2.204' #Replace this with your version of DotNet Core
# Same as CLI dotnet restore - Restores packages to run the app 
# (shouldn't be needed in DotNet Core 2.2 build already does it implicitly)
- script: dotnet restore
  displayName: 'dotnet restore'
# Same as CLI dotnet build - Builds the app  
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build'
# Run the tests found in the app directory
- script: dotnet test
  displayName: 'dotnet test'
# Task to package and copy the zip to the ArtifactStagingDirectory 
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
# Task to publish the zip and generate a artifact named drop
- task: PublishBuildArtifacts@1
  displayName: PUBLISH
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop